# Avisa o Spring para ler o arquivo .env na raiz do projeto
spring.config.import=optional:file:.env

# Configurações do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:meubanco
spring.datasource.driverClassName=org.h2.Driver

# Nossas variáveis de ambiente seguras
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}